# -*- coding: utf-8 -*-
"""Hashing. ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uZ6OaXfMMzZiTodVZx3YdOKAsUilbW3Z
"""

#Group Anagrams
from collections import defaultdict

def groupAnagrams(strs):
    anagrams = defaultdict(list)
    for s in strs:
        key = tuple(sorted(s))
        anagrams[key].append(s)
    return list(anagrams.values())

#Top K Frequent Elements
from collections import Counter

def topKFrequent(nums, k):
    count = Counter(nums)
    return [item for item, _ in count.most_common(k)]

#Subarray Sum Equals K
from collections import defaultdict

def subarraySum(nums, k):
    prefix_sum = 0
    count = 0
    sums = defaultdict(int)
    sums[0] = 1

    for num in nums:
        prefix_sum += num
        count += sums[prefix_sum - k]
        sums[prefix_sum] += 1

    return count