# -*- coding: utf-8 -*-
"""Two Pointers / Sliding Window.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KUak0_va6JBCrLBUCWYEhFK9CY3fBy5N
"""

#Valid Palindrome
def isPalindrome(s):
    s = ''.join(c.lower() for c in s if c.isalnum())
    return s == s[::-1]

#Container With Most Water
def maxArea(height):
    left, right = 0, len(height) - 1
    max_area = 0

    while left < right:
        max_area = max(max_area, min(height[left], height[right]) * (right - left))
        if height[left] < height[right]:
            left += 1
        else:
            right -= 1
    return max_area

# Minimum Window Substring
from collections import Counter

def minWindow(s, t):
    if not t or not s:
        return ""

    t_count = Counter(t)
    window = {}
    have, need = 0, len(t_count)
    res, res_len = [-1, -1], float("inf")
    left = 0

    for right in range(len(s)):
        char = s[right]
        window[char] = window.get(char, 0) + 1

        if char in t_count and window[char] == t_count[char]:
            have += 1

        while have == need:
            if (right - left + 1) < res_len:
                res = [left, right]
                res_len = right - left + 1

            window[s[left]] -= 1
            if s[left] in t_count and window[s[left]] < t_count[s[left]]:
                have -= 1
            left += 1

    l, r = res
    return s[l:r+1] if res_len != float("inf") else ""